import os


def crear_config_files(app_dir: str, target_path: str, nombre: str):
    """Genera app/config.py, .env.example y README.md para Supabase."""

    # 1. app/config.py
    with open(os.path.join(app_dir, "config.py"), "w", encoding="utf-8") as f:
        f.write(
            "import os\n"
            "from dotenv import load_dotenv\n\n"
            "load_dotenv()\n\n"
            "# Configuración CORS\n"
            'CORS_ORIGINS_RAW = os.getenv("CORS_ORIGINS", "http://localhost:3000,http://localhost:5173,http://127.0.0.1:8000")\n'
            'CORS_ORIGINS = [origin.strip() for origin in CORS_ORIGINS_RAW.split(",") if origin.strip()]\n\n'
            "# Credenciales Supabase\n"
            'SUPABASE_URL = os.getenv("SUPABASE_URL", "")\n'
            'SUPABASE_KEY = os.getenv("SUPABASE_KEY", "")\n'
        )

    # 2. .env.example
    with open(
        os.path.join(target_path, ".env.example"), "w", encoding="utf-8"
    ) as f:
        f.write(
            "# Configuración CORS\n"
            "CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:8000\n\n"
            "# Credenciales de tu proyecto en Supabase (Project Settings -> API)\n"
            "SUPABASE_URL=https://tu-proyecto.supabase.co\n"
            "SUPABASE_KEY=tu-anon-key-o-service-role-key\n"
        )

    # 3. README.md
    with open(
        os.path.join(target_path, "README.md"), "w", encoding="utf-8"
    ) as f:
        f.write(
            f"# {nombre}\n\n"
            "API REST construida con FastAPI y Supabase.\n\n"
            "## Configuración previa en Supabase\n"
            "1. Crea un proyecto en [Supabase](https://supabase.com/).\n"
            "2. En el Editor SQL de Supabase, crea la tabla `items`:\n"
            "```sql\n"
            "create table items (\n"
            "  id bigint generated by default as identity primary key,\n"
            "  title text not null,\n"
            "  description text,\n"
            "  price numeric not null,\n"
            "  created_at timestamp with time zone default timezone('utc'::text, now()) not null\n"
            ");\n"
            "```\n"
            "3. Copia la URL del proyecto y la API Key (Anon Key) a tu archivo `.env`.\n\n"
            "## Ejecución Local\n"
            "1. Copia `.env.example` a `.env`: `cp .env.example .env`\n"
            "2. Instala dependencias: `pip install -r requirements.txt`\n"
            "3. Inicia la API: `python run.py`\n"
            "4. Documentación interactiva en `http://127.0.0.1:8000/docs`\n"
        )